---
- include: tasks/services-list.yml
  static: false
  when: bind_directories | length > 0

- include: tasks/services-stop.yml
  static: false
  with_items: "{{ bind_directories_services }}"
  loop_control:
    loop_var: service
    label: "{{ service }}"
  when: bind_directories_services | length > 0

- include: tasks/directory.yml
  static: false
  with_items: "{{ bind_directories }}"
  loop_control:
    loop_var: bind_directory
    label: "{{ bind_directory.mount_point }}"
  when: bind_directories | length > 0

- include: tasks/services-start.yml
  static: false
  with_items: "{{ bind_directories_services }}"
  loop_control:
    loop_var: service
    label: "{{ service }}"
  when: bind_directories_services | length > 0
